# Generated by Django 5.2.3 on 2025-08-12 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1)),
                ('pron1', models.CharField()),
                ('mean1', models.CharField()),
                ('pron2', models.CharField(null=True)),
                ('mean2', models.CharField(null=True)),
                ('jlpt', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rkmath', models.CharField(max_length=2, null=True)),
                ('jaltap', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(34)])),
                ('somatome', models.IntegerField()),
            ],
        ),
    ]
