# Generated by Django 5.2.3 on 2025-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='character',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
