# Generated by Django 5.2.5 on 2025-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjis', '0002_alter_kanji_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='mean2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='pron2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
