# Generated by Django 5.2.3 on 2025-10-28 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjis', '0003_alter_kanji_mean2_alter_kanji_pron2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='jaltap',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)]),
        ),
    ]
